
version: '3.1'

services:

  postgresdb:
    image: postgres
    restart: always
    env_file:
      - pass.env
    volumes:
      - postgresdb-volume:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  # mysqldb-volume: {}
  postgresdb-volume: {}
